server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.migration/changelog.xml
    enabled: ${LIQUIBASE_ENABLED}