#ONLY FOR LOCAL DEVELOPMENT
version: '2'
services:
  hikeapp-db:
    image: mariadb:10.5.3
    environment:
      - MYSQL_USER=hikeapp
      - MYSQL_PASSWORD=hikeapp
      - MYSQL_DATABASE=hikeapp
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp